### ISSUE TITLE
iwould like to install this on my homelab to try it out

### ISSUE THREAD

**Issue by milal2019** [MatKollar/Invoice_OCR_app#39]
iam still new in this iwant to try this app but docker compose dont work please help

**Comment by MatKollar** [comment]
You need to have a container engine tool installed and running on your machine. For example, you can use the [Docker Desktop](https://www.docker.com/products/docker-desktop/) app.

**Comment by milal2019** [comment]
hello the back  end launch and turn off on docker and gives this error 2024-07-22 03:53:54 RuntimeError: module compiled against ABI version 0x1000009 but this version of numpy is 0x2000000
2024-07-22 03:53:54 Traceback (most recent call last):
2024-07-22 03:53:54   File "/app/run.py", line 1, in <module>
2024-07-22 03:53:54     from app import create_app
2024-07-22 03:53:54   File "/app/app/__init__.py", line 7, in <module>
2024-07-22 03:53:54     from app.models import User, UserRole
2024-07-22 03:53:54   File "/app/app/models.py", line 7, in <module>
2024-07-22 03:53:54     from app.utils.utils import get_uuid
2024-07-22 03:53:54   File "/app/app/utils/utils.py", line 3, in <module>
2024-07-22 03:53:54     import cv2
2024-07-22 03:53:54   File "/usr/local/lib/python3.10/site-packages/cv2/__init__.py", line 181, in <module>
2024-07-22 03:53:54     bootstrap()
2024-07-22 03:53:54   File "/usr/local/lib/python3.10/site-packages/cv2/__init__.py", line 153, in bootstrap
2024-07-22 03:53:54     native_module = importlib.import_module("cv2")
2024-07-22 03:53:54   File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
2024-07-22 03:53:54     return _bootstrap._gcd_import(name[level:], package, level)
2024-07-22 03:53:54 ImportError: numpy.core.multiarray failed to import
2024-07-22 03:54:05 RuntimeError: module compiled against ABI version 0x1000009 but this version of numpy is 0x2000000
2024-07-22 03:54:05 Traceback (most recent call last):
2024-07-22 03:54:05   File "/app/run.py", line 1, in <module>
2024-07-22 03:54:05     from app import create_app
2024-07-22 03:54:05   File "/app/app/__init__.py", line 7, in <module>
2024-07-22 03:54:05     from app.models import User, UserRole
2024-07-22 03:54:05   File "/app/app/models.py", line 7, in <module>
2024-07-22 03:54:05     from app.utils.utils import get_uuid
2024-07-22 03:54:05   File "/app/app/utils/utils.py", line 3, in <module>
2024-07-22 03:54:05     import cv2
2024-07-22 03:54:05   File "/usr/local/lib/python3.10/site-packages/cv2/__init__.py", line 181, in <module>
2024-07-22 03:54:05     bootstrap()
2024-07-22 03:54:05   File "/usr/local/lib/python3.10/site-packages/cv2/__init__.py", line 153, in bootstrap
2024-07-22 03:54:05     native_module = importlib.import_module("cv2")
2024-07-22 03:54:05   File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
2024-07-22 03:54:05     return _bootstrap._gcd_import(name[level:], package, level)
2024-07-22 03:54:05 ImportError: numpy.core.multiarray failed to import
2024-07-22 03:54:43 RuntimeError: module compiled against ABI version 0x1000009 but this version of numpy is 0x2000000
2024-07-22 03:54:43 Traceback (most recent call last):
2024-07-22 03:54:43   File "/app/run.py", line 1, in <module>
2024-07-22 03:54:43     from app import create_app
2024-07-22 03:54:43   File "/app/app/__init__.py", line 7, in <module>
2024-07-22 03:54:43     from app.models import User, UserRole
2024-07-22 03:54:43   File "/app/app/models.py", line 7, in <module>
2024-07-22 03:54:43     from app.utils.utils import get_uuid
2024-07-22 03:54:43   File "/app/app/utils/utils.py", line 3, in <module>
2024-07-22 03:54:43     import cv2
2024-07-22 03:54:43   File "/usr/local/lib/python3.10/site-packages/cv2/__init__.py", line 181, in <module>
2024-07-22 03:54:43     bootstrap()
2024-07-22 03:54:43   File "/usr/local/lib/python3.10/site-packages/cv2/__init__.py", line 153, in bootstrap
2024-07-22 03:54:43     native_module = importlib.import_module("cv2")
2024-07-22 03:54:43   File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
2024-07-22 03:54:43     return _bootstrap._gcd_import(name[level:], package, level)
2024-07-22 03:54:43 ImportError: numpy.core.multiarray failed to import
2024-07-22 04:09:06 RuntimeError: module compiled against ABI version 0x1000009 but this version of numpy is 0x2000000
2024-07-22 04:09:06 Traceback (most recent call last):
2024-07-22 04:09:06   File "/app/run.py", line 1, in <module>
2024-07-22 04:09:06     from app import create_app
2024-07-22 04:09:06   File "/app/app/__init__.py", line 7, in <module>
2024-07-22 04:09:06     from app.models import User, UserRole
2024-07-22 04:09:06   File "/app/app/models.py", line 7, in <module>
2024-07-22 04:09:06     from app.utils.utils import get_uuid
2024-07-22 04:09:06   File "/app/app/utils/utils.py", line 3, in <module>
2024-07-22 04:09:06     import cv2
2024-07-22 04:09:06   File "/usr/local/lib/python3.10/site-packages/cv2/__init__.py", line 181, in <module>
2024-07-22 04:09:06     bootstrap()
2024-07-22 04:09:06   File "/usr/local/lib/python3.10/site-packages/cv2/__init__.py", line 153, in bootstrap
2024-07-22 04:09:06     native_module = importlib.import_module("cv2")
2024-07-22 04:09:06   File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
2024-07-22 04:09:06     return _bootstrap._gcd_import(name[level:], package, level)
2024-07-22 04:09:06 ImportError: numpy.core.multiarray failed to import
2024-07-22 04:10:02 RuntimeError: module compiled against ABI version 0x1000009 but this version of numpy is 0x2000000
2024-07-22 04:10:02 Traceback (most recent call last):
2024-07-22 04:10:02   File "/app/run.py", line 1, in <module>
2024-07-22 04:10:02     from app import create_app
2024-07-22 04:10:02   File "/app/app/__init__.py", line 7, in <module>
2024-07-22 04:10:02     from app.models import User, UserRole
2024-07-22 04:10:02   File "/app/app/models.py", line 7, in <module>
2024-07-22 04:10:02     from app.utils.utils import get_uuid
2024-07-22 04:10:02   File "/app/app/utils/utils.py", line 3, in <module>
2024-07-22 04:10:02     import cv2
2024-07-22 04:10:02   File "/usr/local/lib/python3.10/site-packages/cv2/__init__.py", line 181, in <module>
2024-07-22 04:10:02     bootstrap()
2024-07-22 04:10:02   File "/usr/local/lib/python3.10/site-packages/cv2/__init__.py", line 153, in bootstrap
2024-07-22 04:10:02     native_module = importlib.import_module("cv2")
2024-07-22 04:10:02   File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
2024-07-22 04:10:02     return _bootstrap._gcd_import(name[level:], package, level)
2024-07-22 04:10:02 ImportError: numpy.core.multiarray failed to import
2024-07-22 04:22:28 RuntimeError: module compiled against ABI version 0x1000009 but this version of numpy is 0x2000000
2024-07-22 04:22:28 Traceback (most recent call last):
2024-07-22 04:22:28   File "/app/run.py", line 1, in <module>
2024-07-22 04:22:28     from app import create_app
2024-07-22 04:22:28   File "/app/app/__init__.py", line 7, in <module>
2024-07-22 04:22:28     from app.models import User, UserRole
2024-07-22 04:22:28   File "/app/app/models.py", line 7, in <module>
2024-07-22 04:22:28     from app.utils.utils import get_uuid
2024-07-22 04:22:28   File "/app/app/utils/utils.py", line 3, in <module>
2024-07-22 04:22:28     import cv2
2024-07-22 04:22:28   File "/usr/local/lib/python3.10/site-packages/cv2/__init__.py", line 181, in <module>
2024-07-22 04:22:28     bootstrap()
2024-07-22 04:22:28   File "/usr/local/lib/python3.10/site-packages/cv2/__init__.py", line 153, in bootstrap
2024-07-22 04:22:28     native_module = importlib.import_module("cv2")
2024-07-22 04:22:28   File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
2024-07-22 04:22:28     return _bootstrap._gcd_import(name[level:], package, level)
2024-07-22 04:22:28 ImportError: numpy.core.multiarray failed to import
